name: Build Mac Installer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'  # Match your .NET MAUI version
      - name: Install .NET MAUI Workloads
        run: |
          dotnet workload install maui

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.0'

      # Restore only the MAUI project instead of the whole solution
      - name: Restore NuGet Packages
        run: dotnet restore "./source/Transcriber/Transcriber.Maui/Transcriber.Maui.csproj"

      - name: Build MacCatalyst App
        run: dotnet publish "./source/Transcriber/Transcriber.Maui/Transcriber.Maui.csproj" -f net9.0-maccatalyst -c Release -o ./publish

      - name: Upload DMG Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mac-installer
          path: |
            **/bin/Release/net9.0-macos/publish/*.app